// <auto-generated />
using System;
using AdapterImec.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdapterImec.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdapterImec.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Creator")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Creator");

                    b.Property<string>("CustomerScheme")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("CustomerScheme");

                    b.Property<string>("CustomerValue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("CustomerValue");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("timestamp")
                        .HasColumnName("DateReceived");

                    b.Property<string>("FileContent")
                        .HasColumnType("text")
                        .HasColumnName("FileContent");

                    b.Property<string>("MessageId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("MessageId");

                    b.Property<string>("MessageType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("MessageType");

                    b.Property<string>("ProvidingCompanyScheme")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ProvidingCompanyScheme");

                    b.Property<string>("ProvidingCompanyValue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ProvidingCompanyValue");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
